### ISSUE TITLE
syslogd stuck

### ISSUE THREAD

**Issue by akangaziz** [nimmis/docker-alpine-micro#1]
congrats for your great work by providing this repo! 
anyway, i try it and stuck in rsyslogd process after run the image. pls advise.
		
	

    sh-3.2# pwd
	 /dockertry/docker-alpine-micro/3.6
    sh-3.2# docker build -t test/alpine-with-init:1.0 .
    Sending build context to Docker daemon   7.68kB
    Step 1/8 : FROM alpine:3.6
     ---> 7328f6f8b418
    Step 2/8 : MAINTAINER nimmis <kjell.havneskold@gmail.com>
     ---> Using cache
     ---> 0f07abfbf21a
    Step 3/8 : COPY root/. /
     ---> Using cache
     ---> c24e1fe401b6
    Step 4/8 : RUN echo "@community http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories &&     echo "@testing http://dl-4.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories &&     apk update && apk upgrade &&     apk add ca-certificates rsyslog logrotate runit &&     mkdir -p /etc/BUILDS/ &&     printf "Build of nimmis/alpine-micro:3.6, date: %s\n"  `date -u +"%Y-%m-%dT%H:%M:%SZ"` > /etc/BUILDS/alpine-micro &&     apk add curl &&     cd /tmp &&     curl -Ls https://github.com/nimmis/docker-utils/archive/master.tar.gz | tar xfz - &&     ./docker-utils-master/install.sh &&     rm -Rf ./docker-utils-master &&     curl -Ls https://github.com/nimmis/backup/archive/master.tar.gz | tar xfz - &&     ./backup-master/install.sh all &&     rm -Rf ./backup-master &&     apk del curl &&     sed  -i "s|\*.emerg|\#\*.emerg|" /etc/rsyslog.conf &&     rm -rf /var/cache/apk/*
     ---> Using cache
     ---> 95b5a8a9b666
    Step 5/8 : VOLUME /backup
     ---> Using cache
     ---> 9f46803f6ed0
    Step 6/8 : ENV HOME /root
     ---> Using cache
     ---> 4d29ac5b0b2d
    Step 7/8 : WORKDIR /root
     ---> Using cache
     ---> 5ad2f43dfac0
    Step 8/8 : CMD /boot.sh
     ---> Using cache
     ---> 862d5aac9f07
    Successfully built 862d5aac9f07
    Successfully tagged test/alpine-with-init:1.0
    
        sh-3.2# docker image ls
        REPOSITORY                      TAG                 IMAGE ID            CREATED             SIZE
       test/alpine-with-init           1.0                 862d5aac9f07        13 minutes ago      8.41MB
        golang                          1.8.3-alpine        310e63753884        3 weeks ago         257MB
        alpine                          3.6                 7328f6f8b418        3 weeks ago         3.97MB
        alpine                          latest              7328f6f8b418        3 weeks ago         3.97MB
        sh-3.2# docker run -it --rm test/alpine-with-init:1.0
        Run scripts in /etc/run_once
        Build of nimmis/alpine-micro:3.6, date: 2017-07-19T03:57:37Z
        Run scripts is /etc/run_always
        Started runsvdir, PID is 13
        wait for processes to start....
        crond[18]: crond (busybox 1.26.2) started, log level 8
        rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
        rsyslogd: activation of module imklog.so failed [v8.26.0 try http://www.rsyslog.com/e/2145 ]
        run: crond: (pid 18) 5s
        run: rsyslogd: (pid 17) 5s`

**Comment by noogen** [comment]
Because docker/container can't do imklog since access to /proc is mostly readonly?  Fix:
```
sed -i 's/$ModLoad imklog/#$ModLoad imklog/' /etc/rsyslog.conf
sed -i 's/$KLogPermitNonKernelFacility on/#$KLogPermitNonKernelFacility on/' /etc/rsyslog.conf
```

**Comment by nimmis** [comment]
It works as intended, the consol output is from the simulated init process and is only output. Any interaction inside the container should be done thru a shell. Running the container without the -d is only usable for testing as it is constructed to be run as a a daemon

>docker run -d --name test nimmis/alpine-micro

you can check that everything worked ok with

> docker logs -f name

to work inside the container you should run a shell

> docker exec -ti test /bin/sh

**Comment by nimmis** [comment]
Thanks @noogen for the fix, will implement it
